/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.Lista_Grupos;
import Capa_Datos.Lista_Matricula;
import Capa_Logica.Estudiante;
import Capa_Logica.Matricula;
import Capa_Logica.NivelEstudiado;
import TListas.TLista;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author USER
 */
public class FrmRegistroMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmRegistroMatricula
     */
    public FrmRegistroMatricula() {
        initComponents();
        TLista datos = Lista_Grupos.obtener();
        for (int i = 0; i < datos.Cantidad(); i++) {
            NivelEstudiado lvl = (NivelEstudiado) datos.Obtener(i);
                cboGrupos.addItem("grupo : "+lvl.getCodigoGrupo());
            
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtDocIdentidad = new javax.swing.JTextField();
        btnVerificarDI = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        btnAsignar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboNivelEstudios = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        cboGrupos = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtCodMatricula = new javax.swing.JTextField();
        jclFechaPago = new com.toedter.calendar.JCalendar();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Registrar Matrícula del Estudiante");
        setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Registar Matrícula:");

        jLabel1.setText("Documento De Identidad: ");

        btnVerificarDI.setText("...");
        btnVerificarDI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerificarDIActionPerformed(evt);
            }
        });

        jLabel8.setText("Fecha de Pago:");

        jLabel9.setText("Monto:");

        txtMonto.setEditable(false);

        btnAsignar.setText("Asignar Matrícula");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        jLabel2.setText("Nivel De Estudios:");

        cboNivelEstudios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inglés Para Niños", "Inglés para Jóvenes y Adultos", "Conversation Program", "Spanish Program for foreigners", "Methodology for EFL Teachers", "Teaching English to Kids", "Super Youth" }));

        jLabel3.setText("Grupos Disponibles :");

        jLabel4.setText("Codigo de matricula :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDocIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnVerificarDI))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(69, 69, 69)
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cboNivelEstudios, 0, 1, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cboGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGap(3, 3, 3))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jclFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCodMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)))
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDocIdentidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificarDI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCodMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cboGrupos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cboNivelEstudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jclFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAsignar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public boolean captchaCampos(){
    if(cboGrupos.getSelectedIndex()==-1)
    return false;
    else{
       if(txtCodMatricula.getText().equalsIgnoreCase(null))
           return false;
       else{if(txtMonto.getText().equalsIgnoreCase(null))
            return false;
       else{
            if(txtDocIdentidad.getText().equalsIgnoreCase(null))
                 return false;
            else{
             if(jclFechaPago.getCalendar().equals(null))
                  return false;
             else{
                if(cboNivelEstudios.getSelectedIndex()==-1)
                     return false;}}}}}
return true;}
    private void btnVerificarDIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarDIActionPerformed
         
        if(txtDocIdentidad.getText().equalsIgnoreCase(null))
                JOptionPane.showMessageDialog(rootPane, "DEBE INGRESAR UN DOCUMENTO DE IDENTIDAD", "mensaje del sistema", HEIGHT);
            else{
                String doc =txtDocIdentidad.getText();
                int captcha =Estudiante.verificacionDocIden(doc);
         
            if(captcha ==-1){
                int desicion = JOptionPane.showConfirmDialog(rootPane, "DOCUMENTO DE IDENTIDAD NO ENCONTRADO--¿DESEA REGISTRAR UN NUEO ESTUDIANTE?");
                if(desicion == JOptionPane.YES_OPTION){
                    
                    FrmGestionarEstudiante obj = new FrmGestionarEstudiante();
                    obj.setVisible(true);
                    MenuPrincipal.jPanel1.add(obj);
                }     
            
            }
        }
    }//GEN-LAST:event_btnVerificarDIActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
         String doc =txtDocIdentidad.getText();
        int captcha =Estudiante.verificacionDocIden(doc);
         
            if(captcha ==-1){
                int desicion = JOptionPane.showConfirmDialog(rootPane, "DOCUMENTO DE IDENTIDAD NO ENCONTRADO-- INGRESE UN DOC VALIDO");
                  Matricula m = new Matricula();
                  m.setCodigoGrupo((String) cboGrupos.getSelectedItem());
                  m.setCodigoMatricula(txtCodMatricula.getText());
                  m.setCuotaMensual(Double.parseDouble(txtMonto.getText()));
                  m.setDocumentoIdentidad(txtDocIdentidad.getText());
                  m.setFechaPago(jclFechaPago.getCalendar());
                  m.setCodNivelEstudiado((String) cboNivelEstudios.getSelectedItem());
                  Lista_Matricula.registrarMatricula(m);
        
            }
    }//GEN-LAST:event_btnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnVerificarDI;
    private javax.swing.JComboBox<String> cboGrupos;
    private javax.swing.JComboBox cboNivelEstudios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JCalendar jclFechaPago;
    private javax.swing.JTextField txtCodMatricula;
    private javax.swing.JTextField txtDocIdentidad;
    private javax.swing.JTextField txtMonto;
    // End of variables declaration//GEN-END:variables
}
