/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Capa_Cliente;

import Capa_Datos.Lista_Docentes;
import Capa_Datos.Lista_Estudiantes;
import Capa_Logica.Estudiante;
import TListas.TLista;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class FrmGestionarEstudiante extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmRegistroEstudiante
     */
    public FrmGestionarEstudiante() {
        initComponents();
        jTable1.setModel(tabla());
    }
public DefaultTableModel tabla(){
    DefaultTableModel tablaAlum = new DefaultTableModel();
    TLista datos= Lista_Estudiantes.obtener();
    tablaAlum.addColumn("CODIGO");
    tablaAlum.addColumn("NOMBRE");
    tablaAlum.addColumn("APELLIDOS");
    tablaAlum.addColumn("DOCUMENTO DE IDENTIDAD");
    tablaAlum.addColumn("NACIONALIDAD");
    tablaAlum.addColumn("SEXO");
    tablaAlum.addColumn("TELEFONO");
    Object[] arreglo = new Object [7];
    for (int i = 0; i < datos.Cantidad(); i++) {
        Estudiante E = (Estudiante) datos.Obtener(i);
        arreglo[0]=E.getCodigoEstudiante();
        arreglo[1]=E.getNombre();
        arreglo[2]=E.getApellidos();
        arreglo[3]=E.getDocumentoIdentidad();
        arreglo[4]=E.getNacionalidad();
        arreglo[5]=E.getSexo();
        arreglo[6]=E.getTelefono();
        tablaAlum.addRow(arreglo);
    }
    
return tablaAlum;}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        cboSexo = new javax.swing.JComboBox();
        cboTipoDocumento = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        actualizar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setTitle("Gestionar Estudiante");

        jLabel5.setText("Fecha De Nacimiento:");

        jLabel8.setText("Lista De Estudiantes Registrados:");

        jLabel6.setText("Nacionalidad:");

        txtNacionalidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNacionalidadKeyTyped(evt);
            }
        });

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("Gestionar Estudiantes:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Documento De Identidad: ");

        txtDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDocumentoKeyTyped(evt);
            }
        });

        jLabel2.setText("Tipo De Documento:");

        jLabel3.setText("Nombre:");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Apellidos:");

        jLabel9.setText("Sexo:");

        jLabel10.setText("Teléfono:");

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });

        cboSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Femenino" }));

        cboTipoDocumento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DNI", "Pasaporte" }));

        actualizar.setText("Actualizar");
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel11.setText("Codigo de Estudiante :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel10))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNacionalidad)
                                            .addComponent(txtApellido)
                                            .addComponent(txtNombre)
                                            .addComponent(txtTelefono)
                                            .addComponent(cboSexo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cboTipoDocumento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel1))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                            .addComponent(txtCodigo))))))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboTipoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(actualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        //VALIDACION DESPUES DE CLICkLEAR EL BOTON 
         if(camposNulos()){
      
        //PARTE LOGICA
        String Documento = txtDocumento.getText();
        String tipo = cboTipoDocumento.getSelectedItem().toString();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String nacionalidad = txtNacionalidad.getText();
        String sexo = cboSexo.getSelectedItem().toString();
        int telefono = Integer.parseInt(txtTelefono.getText());
        String codigoEst= txtCodigo.getText();
        Estudiante obj = new Estudiante();
        if (Estudiante.verificacionDocIden(codigoEst) == -1) {
            obj.setDocumentoIdentidad(Documento);
            obj.setTipoDocumento(tipo);
            obj.setNombre(nombre);
            obj.setFechaNacimiento(jDateChooser1.getDateFormatString());
            obj.setApellidos(apellido);
            obj.setNacionalidad(nacionalidad);
            obj.setSexo(sexo);
            obj.setTelefono(telefono);
            obj.setCodigoEstudiante(codigoEst);
            JOptionPane.showMessageDialog(this, "SE REGISTRO AL ESTUDIANTE CORRECTAMENTE", "SISTEMA", JOptionPane.WARNING_MESSAGE);
            Lista_Estudiantes.registrarEst(obj);
             txtCodigo.setText("");
                     txtDocumento.setText("");
                      txtNombre.setText("");
                     txtApellido.setText("");
                     txtTelefono.setText("");
                     txtNacionalidad.setText("");
                     txtCodigo.requestFocus();
                     cboSexo.setSelectedIndex(0);
                     cboTipoDocumento.setSelectedIndex(0);
        } else {
            JOptionPane.showMessageDialog(this, "EL ESTUDIANTE YA EXISTE", "SISTEMA", JOptionPane.ERROR_MESSAGE);
        }}


    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDocumentoKeyTyped
        //VALIDACION TIEMPO REAL
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtDocumento.getText().length() == 8) {
            evt.consume();
        }
    }//GEN-LAST:event_txtDocumentoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        //VALIDACION TIEMPO REAL
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
            /* el metodo consume lo que hace es comer lo que esta 
        dentro de la condcion,por lo tanto intuimos que es lo contrario :)*/
        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        //VALIDACION TIEMPO REAL
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        //VALIDACION TIEMPO REAL
        char c = evt.getKeyChar();
        if (!Character.isDigit(c) || txtTelefono.getText().length() == 9) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtNacionalidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNacionalidadKeyTyped
        //VALIDACION TIEMPO REAL
        char c = evt.getKeyChar();
        if (Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNacionalidadKeyTyped

    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        // TODO add your handling code here: 
        jTable1.setModel(tabla());
    }//GEN-LAST:event_actualizarActionPerformed
public boolean camposNulos(){
 if (txtCodigo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR CODIGO DE ESTUDIANTE", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            txtCodigo.requestFocus();
            return false;
        }
      if (txtDocumento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR DOCUMENTO DE IDENTIDAD", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            txtDocumento.requestFocus();
            return false;
        }
      
        if (cboTipoDocumento.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR TIPO DE DOCUMENTO", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            cboTipoDocumento.requestFocus();
            return false;
        }
        if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR SU NOMBRE ", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            txtNombre.requestFocus();
            return false;
        }
        if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR SU APELLIDO", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            txtApellido.requestFocus();
            return false;
        }

        if (txtNacionalidad.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "DEBE INGRESAR SU NACIONALIDAD", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            txtNacionalidad.requestFocus();
            return false;
        }
        if (cboSexo.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "DEBE SELECCIONAR TIPO DE SEXO", "SISTEMA", JOptionPane.ERROR_MESSAGE);
            cboSexo.requestFocus();
            return false;
        }
        else return true;
}
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(camposNulos()){
       String Documento = txtDocumento.getText();
        String tipo = cboTipoDocumento.getSelectedItem().toString();
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String nacionalidad = txtNacionalidad.getText();
        String sexo = cboSexo.getSelectedItem().toString();
        int telefono = Integer.parseInt(txtTelefono.getText());
        String codigoEst= txtCodigo.getText();
        String date = jDateChooser1.getDateFormatString();
        
        int pos = Lista_Estudiantes.BuscarAlumno(codigoEst);
        if(pos!=-1){
        Estudiante obj = new Estudiante();
            obj.setDocumentoIdentidad(Documento);
            obj.setTipoDocumento(tipo);
            obj.setNombre(nombre);
            obj.setFechaNacimiento(jDateChooser1.getDateFormatString());
            obj.setApellidos(apellido);
            obj.setNacionalidad(nacionalidad);
            obj.setSexo(sexo);
            obj.setTelefono(telefono);
            obj.setCodigoEstudiante(codigoEst);
            JOptionPane.showMessageDialog(this, "SE REGISTRO AL ESTUDIANTE CORRECTAMENTE", "SISTEMA", JOptionPane.WARNING_MESSAGE);
            Lista_Estudiantes.registrarEst(obj);
            
        Lista_Docentes.Modificar(obj,pos);
        
        JOptionPane.showMessageDialog(this,"Se modificaron correctamente los datos del docente","Sistema",JOptionPane.INFORMATION_MESSAGE);
             }
        else
            JOptionPane.showMessageDialog(this,"INGRESE UN ALUMNO EXISTENTE","Sistema",JOptionPane.INFORMATION_MESSAGE);}
             
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if(txtCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(txtCodigo,"REGISTRE ESTUDIANTE A ELIMINAR", "mesaje del sistema", HEIGHT);
        }else{
            int index = Lista_Estudiantes.BuscarAlumno(txtCodigo.getText());
          if(index !=-1){
            TLista datos=Lista_Estudiantes.obtener();
            Estudiante doc =  (Estudiante) datos.Obtener(index); 
            txtNombre.setText(doc.getNombre());
            txtApellido.setText(doc.getApellidos());
            txtDocumento.setText(doc.getDocumentoIdentidad());
            String tipo = (String) cboTipoDocumento.getSelectedItem();
            if(tipo.equalsIgnoreCase("DNI"))
                cboTipoDocumento.setSelectedIndex(0);
            else
                cboTipoDocumento.setSelectedIndex(1);
            txtTelefono.setText(String.valueOf(doc.getTelefono()));
            String sexo = (String) cboSexo.getSelectedItem();
            if(sexo.equalsIgnoreCase("masculino"))
                cboSexo.setSelectedIndex(1);
            else
                cboSexo.setSelectedIndex(2);
            
             int desicion = JOptionPane.showConfirmDialog(txtCodigo, "¿DESEA ELIMINAR EL ESTUDIANTE?", "mensaje del sistema", WIDTH);
                if(desicion == JOptionPane.YES_OPTION)
                {
                    Lista_Estudiantes.eliminar(txtCodigo.getText());
                     txtCodigo.setText("");
                     txtDocumento.setText("");
                      txtNombre.setText("");
                     txtApellido.setText("");
                     txtTelefono.setText("");
                     txtNacionalidad.setText("");
                     txtCodigo.requestFocus();
                     cboSexo.setSelectedIndex(0);
                     cboTipoDocumento.setSelectedIndex(0);
                     JOptionPane.showMessageDialog(txtCodigo, "ESTUDIANTE ELIMINADO", "mesaje del sistema", WIDTH);
                }
          }
          else
              JOptionPane.showMessageDialog(txtCodigo, "ESTUDIANTE NO ENCONTRADO", "mesaje del sistema", WIDTH);
        }
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox cboSexo;
    private javax.swing.JComboBox<String> cboTipoDocumento;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
